apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: edge-apps
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            type: edge
  template:
    metadata:
      name: '{{name}}-rust-collector'
    spec:
      project: default
      source:
        repoURL: https://github.com/rampxxxx/collector.git # MUST BE UPDATED
        targetRevision: HEAD
        path: my-fleet-ops/charts/rust-collector
        helm:
          valueFiles:
            - ../../apps-config/edge-values.yaml
      destination:
        server: '{{server}}'
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
