apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "internal-registry.fullname" . }}
  labels:
    {{- include "internal-registry.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "internal-registry.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "internal-registry.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: registry
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 5000
              name: registry
              protocol: TCP
