apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rust-collector.fullname" . }}
  labels:
    {{- include "rust-collector.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "rust-collector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "rust-collector.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: rust-collector
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: MQTT_BROKER
              value: {{ .Values.env.MQTT_BROKER | quote }}
          ports:
            - name: http
              containerPort: 5678
              protocol: TCP
