apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mqtt-broker.fullname" . }}-config
  labels:
    {{- include "mqtt-broker.labels" . | nindent 4 }}
data:
  mosquitto.conf: |
{{ .Values.config | indent 4 }}
{{- if eq .Values.role "edge" }}
{{ .Values.bridge_config | indent 4 }}
{{- end }}
