apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mqtt-broker.fullname" . }}
  labels:
    {{- include "mqtt-broker.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mqtt-broker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mqtt-broker.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:{{ .Chart.AppVersion }}
          ports:
            - name: mqtt
              containerPort: 1883
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
      volumes:
        - name: config
          configMap:
            name: {{ include "mqtt-broker.fullname" . }}-config
